export type {
  UserRole,
  UserStatus,
  ProviderType,
  AmbulanceStatus,
  BookingStatus,
  Point,
  AmbulanceProvider,
  User,
  Ambulance,
  Hospital,
  Helpline,
  Booking,
} from "@ambulink/types";

// WebSocket Types are sourced from @ambulink/types
export type {
  BookingAssignedPayload,
  BookingCancelledPayload,
  BookingDecisionPayload,
  BookingEventPayload,
  BookingFailedPayload,
  BookingNewPayload,
  DispatcherBookingLogPayload,
  DispatcherBookingPayload,
  DispatcherBookingUpdatePayload,
  DispatcherApprovalResponse,
  DispatcherToServerEvents,
  DriverLocationPayload,
  DriverLocationUpdate,
  DriverToServerEvents,
  ErrorPayload,
  PatientCancelRequest,
  PatientPickupRequest,
  ServerToDispatcherEvents,
  ServerToDriverEvents,
  ServerToPatientEvents,
  SocketErrorPayload,
} from "@ambulink/types";
